"""initial migration

Revision ID: 78c59f05a89
Revises: None
Create Date: 2015-06-02 23:21:57.121318

"""

# revision identifiers, used by Alembic.
revision = '78c59f05a89'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
